### ISSUE TITLE
CSS parsing error

### ISSUE THREAD

**Issue by ehmicky** [Munter/netlify-plugin-subfont#35]
The following error happened in a build:

```
CssSyntaxError: <css input>:1:49: Unknown word
  at Input.error (/opt/build/repo/node_modules/postcss/lib/input.js:130:16)
  at Parser.unknownWord (/opt/build/repo/node_modules/postcss/lib/parser.js:563:22)
  at Parser.other (/opt/build/repo/node_modules/postcss/lib/parser.js:168:12)
  at Parser.parse (/opt/build/repo/node_modules/postcss/lib/parser.js:77:16)
  at Function.parse (/opt/build/repo/node_modules/postcss/lib/parse.js:17:12)
  at getCssRulesByProperty (/opt/build/repo/node_modules/subfont/lib/getCssRulesByProperty.js:43:29)
  at memoizer (/opt/build/repo/node_modules/memoizesync/lib/memoizeSync.js:60:42)
  at memoizeSync (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:174:33)
  at memoizer (/opt/build/repo/node_modules/memoizesync/lib/memoizeSync.js:60:42)
  at traversePreOrder (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:815:13)
  at _.flatten.slice.call.map (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:842:17)
  at Array.map (<anonymous>)
  at traversePreOrder (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:841:16)
  at _.flatten.slice.call.map (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:842:17)
  at Array.map (<anonymous>)
  at traversePreOrder (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:841:16)
  at _.flatten.slice.call.map (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:842:17)
  at Array.map (<anonymous>)
  at traversePreOrder (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:841:16)
  at _.flatten.slice.call.map (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:842:17)
  at Array.map (<anonymous>)
  at traversePreOrder (/opt/build/repo/node_modules/font-tracer/lib/fontTracer.js:841:16)

Error properties
{
  reason: 'Unknown word',
  source: 'bogusselector { justify-content: space-between; text-center }',
  line: 1,
  column: 49,
  input: {
  line: 1,
  column: 49,
  source: 'bogusselector { justify-content: space-between; text-center }'
}
```

I am not sure whether this is a user error or not (wrong CSS). However, if this is a user error, the call should probably be wrapped with a `try`/`catch` block and reported using `utils.build.failBuild()` so that the error is shown as coming from the user, instead of being shown as a bug from this plugin.

**Comment by Munter** [comment]
This is indeed a user error. The addition of `failOnBuild`in aa3b4544289e73d8e2173fac7eb82965301de9d4 is all I can do for this case I think
