### ISSUE TITLE
Failed during font subsetting

### ISSUE THREAD

**Issue by mvhoute** [Munter/netlify-plugin-subfont#50]
```html
9:46:16 AM: ┌────────────────────────────────────────┐
9:46:16 AM: │ Plugin "netlify-plugin-subfont" failed │
9:46:16 AM: └────────────────────────────────────────┘
9:46:16 AM: ​
9:46:16 AM:   Error message
9:46:16 AM:   TypeError: Failed during font subsetting
9:46:16 AM: ​
9:46:16 AM:   ### LOG: ###
9:46:16 AM:   verions: {
9:46:16 AM:     "netlify-build": "1.0.10",
9:46:16 AM:     "netlify-plugin-subfont": "5.0.2",
9:46:16 AM:     "subfont": "5.0.1",
9:46:16 AM:     "assetgraph": "6.0.7"
9:46:16 AM:   }
9:46:16 AM: ​
9:46:16 AM:   Plugin configuration: {
9:46:16 AM:     "entryPoints": [
9:46:16 AM:       "*.html"
9:46:16 AM:     ],
9:46:16 AM:     "recursive": true,
9:46:16 AM:     "inlineFonts": false,
9:46:16 AM:     "inlineCss": false,
9:46:16 AM:     "fontDisplay": "swap",
9:46:16 AM:     "fallbacks": true
9:46:16 AM:   }
9:46:16 AM: ​
9:46:16 AM:   Resolved entry points: [
9:46:16 AM:     "/opt/build/repo/public/404.html",
9:46:16 AM:     "/opt/build/repo/public/index.html"
9:46:16 AM:   ]
9:46:16 AM: ​
9:46:16 AM:   Subfont called with: {
9:46:16 AM:     "recursive": true,
9:46:16 AM:     "inlineFonts": false,
9:46:16 AM:     "inlineCss": false,
9:46:16 AM:     "fontDisplay": "swap",
9:46:16 AM:     "fallbacks": true,
9:46:16 AM:     "inputFiles": [
9:46:16 AM:       "/opt/build/repo/public/404.html",
9:46:16 AM:       "/opt/build/repo/public/index.html"
9:46:16 AM:     ],
9:46:16 AM:     "root": "public",
9:46:16 AM:     "canonicalRoot": "[CENSORED]",
9:46:16 AM:     "inPlace": true
9:46:16 AM:   }
9:46:16 AM: ​
9:46:16 AM:   Cannot read property 'removeChild' of undefined
9:46:16 AM: ​
9:46:16 AM:   Plugin details
9:46:16 AM:   Package:        netlify-plugin-subfont
9:46:16 AM:   Version:        5.0.2
9:46:16 AM:   Repository:     git://github.com/munter/netlify-plugin-subfont.git
9:46:16 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-subfont
9:46:16 AM:   Report issues:  https://github.com/munter/netlify-plugin-subfont/issues
9:46:16 AM: ​
9:46:16 AM:   Error location
9:46:16 AM:   In "onPostBuild" event in "netlify-plugin-subfont" from netlify.toml
9:46:16 AM:       at CssImport.detach (/opt/buildhome/.netlify-build-plugins/node_modules/assetgraph/lib/relations/CssImport.js:71:21)
9:46:16 AM:       at asyncLoadStyleRelationWithFallback (/opt/buildhome/.netlify-build-plugins/node_modules/subfont/lib/subsetFonts.js:272:20)
9:46:16 AM:       at subsetFonts (/opt/buildhome/.netlify-build-plugins/node_modules/subfont/lib/subsetFonts.js:1357:11)
9:46:16 AM:       at async subfont (/opt/buildhome/.netlify-build-plugins/node_modules/subfont/lib/subfont.js:150:24)
9:46:16 AM:       at async onPostBuild (/opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-subfont/lib/index.js:69:5)
```

**Comment by mvhoute** [comment]
Also there's a small typo in the `### LOG: ###` entry: it says `verions` instead of `versions` :-)

**Comment by Munter** [comment]
Thanks for reporting this!

From the stack trace I think you are hitting the exact same case that https://github.com/Munter/netlify-plugin-subfont/issues/32 describes. And Incidentally I just published the fix minutes ago. Could you try to run it again with netlify-plugin-subfont@5.0.3 ?

**Comment by mvhoute** [comment]
Hi @Munter, I've just reinstalled the plugin through the Netlify Build Apps, but it still gave me v5.0.2. AFAIK there isn't a way to force it to use v5.0.3.

**Comment by Munter** [comment]
Apparently I have to bump a version number in a netlify manifest for plugins. That step was new to me, apparently they had just handled that before. I think you can install the plugin yourself as a dev dependency and pin the version number, that should also allow you to stray from netlify defaults

**Comment by mvhoute** [comment]
Tested it again today @Munter, this time with v5.0.3, and the problem seems to be solved! Thanks for your help.
