### ISSUE TITLE
Error: Could not import plugin: The module '/opt/build/repo/node_modules/canvas/build/Release/canvas.node'

### ISSUE THREAD

**Issue by blancomaberino** [Munter/netlify-plugin-subfont#80]
Site won't build.

This is the error I get.

Plugin "netlify-plugin-subfont" internal error

Error: Could not import plugin:
The module '/opt/build/repo/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).

While loading "netlify-plugin-subfont" from Netlify app
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object. (/opt/build/repo/node_modules/canvas/lib/bindings.js:3:18)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object. (/opt/build/repo/node_modules/canvas/lib/canvas.js:9:18)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
at Module.load (internal/modules/cjs/loader.js:977:32)
at Function.Module._load (internal/modules/cjs/loader.js:877:14)
at Module.require (internal/modules/cjs/loader.js:1019:19)
at require (internal/modules/cjs/helpers.js:77:18)
at Object. (/opt/build/repo/node_modules/canvas/index.js:1:16)
at Module._compile (internal/modules/cjs/loader.js:1133:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

**Comment by Munter** [comment]
Did you by any chance change your node version since you installed the dependency?
There is a binary, which is built against your node version at the time of installation, and if you change the node version you will have to reinstall the dependencies.

Could you try clearing your `node_modules` folder and re-install it to see if the error persists?

**Comment by blancomaberino** [comment]
I didn't. In fact, the only thing I did was to install the plugin from netlify's admin panel.
And regarding what you say about clearing my `node_modules` folder, I don't think it's something I can do because we don't upload that file to netlify, we just upload our `package.json` and `package-lock.json` files, then netlify takes care of installing everything when building the site (it's a gatsby site, in case this is relevant)

**Comment by grgcnnr** [comment]
We also have run into this error. It started for us after we explicitly added canvas to outer package for other reasons.
